### ISSUE TITLE
Really interesting work!

### ISSUE THREAD

**Issue by cscott** [joakin/webkipedia#1]
Did you attend my parsoid tutorial during the hackathon?
https://phabricator.wikimedia.org/T105175

Using Parsoid might make it easy to do some more interesting things with the article content, like easily enabling offline spidering and caching.  There's some demo code linked from the slides above.

(I believe the mobile team will eventually be using the Parsoid DOM for mobile views, but I don't think that's been quite done yet.)

Anyway, the Parsoid team (and I) would love to help you with any API questions you have.  I am in particular really passionate about folks developing new client-side front-ends to wikipedia.

**Comment by joakin** [comment]
Hi @cscott! Yes I attended, it was great. In fact I grabbed you when you finished and we talked a bit about it, specially I poked you about how to load the article content since I wasn't sure of how to best do it.

During the hackathon I tried to load the content from the restbase parsoid html, but I found it to be quite "slower" than requesting only the first section from the mobileview api :disappointed: so I run with mobileview for the hackathon.

I'm kind of waiting for the mobile apps guys content service they are working on, that would provide the parsoid dom content already parsed into a nice json for them ios and android apps, then I could just use that service too.

I'm not entirely happy of how the article gets requested/rendered, but for the moment is doing the job. Essentially now I'm having to replicate hacks that the apps folks have already done to render the content nicely on mobile (hide certain things, collapse infobox, and there's probably a lot more I don't know about).

Regarding offline plans, I have to add a indexedDB polyfill (like local forage) and structure a bit better how I'm saving the "DB" data, and then I'll look into making the site offline using serviceworker or app cache (with something like gr2m/appcache-nanny maybe).

I'm going to keep developing this as an experimentation project, with the hopes that it get's a bit more mature and that it can be useful for maybe replacing the old cordova app for firefoxOS or windows phones, maybe a desktop app with electron, or a niche version of (mobile) web wikipedia.

As the tech stack you can see I'm using clojurescript with a react.js wrapper, it is fairly interesting and different :grinning: 

If you have any suggestions please tell me, it is hard to find people interested in these kind of things.
